### ISSUE TITLE
Pointing Domain Name

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#12]
I'll need some education on how best to point the domain name to the heroku instance. I'm assuming an A Record/IP address for the primary domain or similar? 

Plan is to point the primary domain name to the prelaunchr app and once finished, point it back to their godaddy account where the full website will reside. After the promo is over we may want to setup a subdomain and point that to the prelaunchr app just for a week or so as a reference if need be.

**Comment by jchapin** [comment]
@cbradshaw what's the domain name going to be?

We'll need to let Heroku know to receive traffic for that domain name at the production app endpoint. We can go ahead and have that subdomain setup to be received at the same application...

promo.whateverthedomainnameis.com

Then they're going to want to setup a CNAME for www.domainname.com in their DNS records, and point that to ni-prelauncer-production.herokuapp.com

I would also suggest getting an inexpensive SSL certificate from thesslstore.com

**Comment by cbradshaw** [comment]
http://www.themindfulnessedge.com/

duly noted on the rest and promo.themindfulnessedge.com sounds good for the post-campaign subdomain.

**Comment by jchapin** [comment]
```
Adding www.themindfulnessedge.com to ni-prelaunchr-production... done
 ▸    WARNING: Configure your app's DNS provider to point to the DNS Target ni-prelaunchr-production.herokuapp.com.
 ▸    For help, see https://devcenter.heroku.com/articles/custom-domains
peaty:prelaunchr_for_ni jchapin$ heroku domains:add promo.themindfulnessedge.com --app=ni-prelaunchr-production
Adding promo.themindfulnessedge.com to ni-prelaunchr-production... done
 ▸    WARNING: Configure your app's DNS provider to point to the DNS Target ni-prelaunchr-production.herokuapp.com.
 ▸    For help, see https://devcenter.heroku.com/articles/custom-domains
peaty:prelaunchr_for_ni jchapin$ heroku domains --app=ni-prelaunchr-production
=== ni-prelaunchr-production Heroku Domain
ni-prelaunchr-production.herokuapp.com

=== ni-prelaunchr-production Custom Domains
Domain Name                   DNS Target
────────────────────────────  ──────────────────────────────────────
www.themindfulnessedge.com    ni-prelaunchr-production.herokuapp.com
promo.themindfulnessedge.com  ni-prelaunchr-production.herokuapp.com
```

**Comment by jchapin** [comment]
@cbradshaw CNAME records can be pointed to ni-prelaunchr-production.herokuapp.com

In addition we might want to make sure there's a forward setup from the apex of the domain to www.

```
On GoDaddy, use the "Forwarding" feature to setup a forward from yourdomain.com to www.yourdomain.com. The forwarding feature can be accessed in the Domain Manager at the bottom of the "Domain Information" section:
```

**Comment by jchapin** [comment]
Closing.
