### ISSUE TITLE
user_mailer/signup_email.html.erb still references harry's shaving stuff.

### ISSUE THREAD

**Issue by RanSolo** [capitaltechnologyservices/prelaunchr_for_ni#15]
<img width="193" alt="screenshot 2016-02-19 10 22 01" src="https://cloud.githubusercontent.com/assets/6284142/13187389/5a807a7c-d710-11e5-89d2-c67ee4ac2530.png">
<img width="972" alt="screenshot 2016-02-19 10 22 11" src="https://cloud.githubusercontent.com/assets/6284142/13187388/5a7eec0c-d710-11e5-859b-23967ad7d374.png">

**Comment by jchapin** [comment]
I killed some of this content because it was preventing the e-mail from being sent cleanly. So the message is a very blank slate now.

**Comment by jchapin** [comment]
Addressed.
