### ISSUE TITLE
Make form fields required

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#29]
looks like users can click through without filling out all the fields. all should be required and ideally kick out an error highlighting the missing field(s) via text or red border or whatever. Email should validate as an actual email address as well if it already doesn't.

**Comment by cbradshaw** [comment]
Looks like right now, if a field isn't filled out correctly, it just kicks back to the home page.

**Comment by RanSolo** [comment]
:+1:

**Comment by jchapin** [comment]
@cbradshaw might be the IP filtering / restriction they put some rather harsh controls on spam in the app.

**Comment by RanSolo** [comment]
So i'm not having any luck making the behavior change with just rails validations. It still goes back to the splash screen with no errors being shown.

<img width="1110" alt="screenshot 2016-02-26 09 03 20" src="https://cloud.githubusercontent.com/assets/6284142/13355811/d8c95488-dc67-11e5-84fe-adacdda94027.png">

<img width="1214" alt="screenshot 2016-02-26 09 04 37" src="https://cloud.githubusercontent.com/assets/6284142/13355849/fb705734-dc67-11e5-82cd-6e615e3836f6.png">

**Comment by cbradshaw** [comment]
I can try to implement some javascript validation if that would be easier.

**Comment by jchapin** [comment]
I think @RanSolo was going to knock it out with HTML5's required attribute and possibly jQuery's validate extension. We had a chat going on in the #developers channel about it.

**Comment by cbradshaw** [comment]
Cool. I was planning on using validate as well. I’ll hold off so just let me know if I need to implement anything.
