### ISSUE TITLE
Scale Up Production Server?

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#5]
client expects “millions” of visits so server needs to be able to handle a huge surge. I doubt that numbers aren’t going to be in the millions. I’d expect more like potentially thousands per day at the most but still need to prepare for massive traffic just to please them. Whatever you think is best here works. Again, this thing will be up for less than a week.

**Comment by jchapin** [comment]
@cbradshaw no problem. We'll be able to switch to production dynos and scale up the memory and number of instances based on demand once we get going. The process may be something like with Nisolo that we need to observe and then correct for the problem, as you mentioned... we can't predict the future so we don't know what the demand is going to be like yet... But we do have a plan for responding to increased traffic.

We'll be watching the Heroku metrics carefully on launch day.

![screen shot 2016-02-18 at 3 18 04 pm](https://cloud.githubusercontent.com/assets/116142/13156891/d9829170-d652-11e5-9396-5e27d1174144.png)

**Comment by jchapin** [comment]
We probably should switch over to a production database in advance of launch. I can do that now.

**Comment by jchapin** [comment]
```
peaty:prelaunchr_for_ni jchapin$ heroku pg --app=ni-prelauncer-production
=== HEROKU_POSTGRESQL_CHARCOAL_URL, DATABASE_URL
Plan:        Hobby-basic
Status:      Available
Connections: 2/20
PG Version:  9.4.6
Created:     2016-02-18 20:33 UTC
Data Size:   7.0 MB
Tables:      6
Rows:        13/10000000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported
Add-on:      postgresql-shallow-57022
```

We can support 10,000,000 rows / records. If there's a need to beef up the PostgreSQL services, we can also do that after launch in a few minutes.

**Comment by cbradshaw** [comment]
awesome. good to know just in case the crazy numbers actually do happen.

**Comment by jchapin** [comment]
Closing.
