### ISSUE TITLE
Verify that we can get a CSV export file

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#6]
just want to make doubly sure that we can get all of the appropriate data out at the end. Each entry should have first name, last name, email address, link to file uploaded, number of shares, etc. The app should handle this by default though we're also adding first/last name and upload so those need to be accounted for.

**Comment by cbradshaw** [comment]
I should add that per the readme, the data will be sectioned out by sharing level (1,2,3,4,etc) but need to double check that the exported file will be easy for client to segment into different email lists in MailChimp.

**Comment by jchapin** [comment]
@cbradshaw do we just need a dump of the data in CSV format at the end of the run? Yes we can do that without developing a whole user interface for exporting the file if all we care about is the raw data.

Is there a need for someone to be able to perform a self-service export of a CSV file?

**Comment by cbradshaw** [comment]
The app has a rake: something-or-other function that should export all the data to csv, nicely formatted. Details are in the readme. I couldn’t get it to work locally. No need for custom UI. there is an admin interface but probably doesn’t have export functionality. As long as we can get him a csv that he can sort by sharing level, we’re good. a db export to csv should work assuming all of the data is organized well.

**Comment by jchapin** [comment]
The rake was writes to the local filesystem, we'll change the rake task to pipe the output to standard output, or use ActiveAdmin for the export of records.

**Comment by jchapin** [comment]
Closing.
