### ISSUE TITLE
Email User when they initially fill out form?

### ISSUE THREAD

**Issue by cbradshaw** [capitaltechnologyservices/prelaunchr_for_ni#9]
Client mentioned that he wants to email users when they first fill out the form (name, email, receipt upload) and send links to the various rewards they'll receive. I can handle the links via the email template as the email should be entirely static (other than the user's unique link maybe). Not sure if the system automatically sends an email to the user or not so want to double check that once it's up and running. I think it probably does based on what I've seen.

**Comment by jchapin** [comment]
@RanSolo I recommend dropping the letter_opener gem into the dev / test environment to see if e-mails are sent during the process and then customizing said e-mail. You've used that one in WCW.

**Comment by RanSolo** [comment]
@cbradshaw the sign_up mailer template still references Harry's shaving stuff...

**Comment by cbradshaw** [comment]
10-4. I hadn’t touched that at all yet as I was waiting on client direction and wasn’t sure which files to edit. Were you able to test and receive an email? If so could you forward that on?

**Comment by RanSolo** [comment]
@cbradshaw yes, I have a pr in right now that get's the mailer up and running and uses letter_opener gem so it will be easier to style.
